### ISSUE TITLE
missing dependency python-gi on autopoweroff-gui

### ISSUE THREAD

**Issue by it-jonas** [deragon/autopoweroff#32]
Hello,
on lmde 5 and linux mint 20.3 python-gi was renamed to python3-gi this prevents autopoweroff-gui from installing successfully as the dependency can't be fulfilled. Seems like #17 had the same problem.

**Comment by deragon** [comment]
Fixed with commit #https://github.com/deragon/autopoweroff/commit/125a7f8de009b7236b65e1690fd57cac23c67cf4.

**Comment by creativecoder** [comment]
I'm still seeing this issue using the 4.1.1 deb package, using Pop!_OS 22.04 LTS

```shell
$ wget https://github.com/deragon/autopoweroff/releases/download/4.1.1/autopoweroff-gui_4.1.1_all.deb
$ sudo apt install ./*autopoweroff*.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'autopoweroff-gui' instead of './autopoweroff-gui_4.1.1_all.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 autopoweroff-gui : Depends: autopoweroff but it is not installable
                    Depends: python-gi but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by deragon** [comment]
Yes, me too since I moved to Ubuntu 22.04 LTS... Ugh... dependencies change with distributions.  I need to start creating more distribution dependent packages.  Need time to do this...

**Comment by deragon** [comment]
Fixed (hoperfully) in [release 4.1.2](https://github.com/deragon/autopoweroff/releases/tag/4.1.2).  Please provide feedback.

**Comment by creativecoder** [comment]
I tried install both 4.1.2 and 4.2.0 on Pop!_OS.

First there was an message about missing `python-gi-dev`, so I installed that. Now I'm getting this

```
$ sudo dpkg -i Downloads/autopoweroff-gui_4.2.0_all-popos-22.04.deb 
Selecting previously unselected package autopoweroff-gui.
(Reading database ... 403662 files and directories currently installed.)
Preparing to unpack .../autopoweroff-gui_4.2.0_all-popos-22.04.deb ...
Unpacking autopoweroff-gui (4.2.0) ...
dpkg: dependency problems prevent configuration of autopoweroff-gui:
 autopoweroff-gui depends on autopoweroff-daemon; however:
  Package autopoweroff-daemon is not installed.

dpkg: error processing package autopoweroff-gui (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Errors were encountered while processing:
 autopoweroff-gui
```

**Comment by deragon** [comment]
@creativecoder , the command tell you what the problem is.  :)

_Package autopoweroff-daemon is not installed._

You have to install the daemon too.  The GUI does not include the daemon.

Download the daemon too and then try:

`sudo apt install autopoweroff-daemon_4.2.0_all-popos-22.04.deb  autopoweroff-gui_4.2.0_all-popos-22.04.deb`

If you use `apt` instead of `dpkg`, the dependencies will be automatically loaded.  Always use `apt`, never `dpkg`.

**Comment by molohov** [comment]
This is the error I get on Ubuntu Server 22.04:

```
sudo apt install ./autopoweroff-gui_4.2.0_all-ubuntu-20.04.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 autopoweroff-gui : Depends: python-gi but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

**Comment by holocronweaver** [comment]
Still an issue in Ubuntu desktop 22.04 with autopoweroff 4.2.0:

```
$ sudo dpkg -i autopoweroff-gui_4.2.0_all-ubuntu-20.04.deb
Selecting previously unselected package autopoweroff-gui.
(Reading database ... 335986 files and directories currently installed.)
Preparing to unpack autopoweroff-gui_4.2.0_all-ubuntu-20.04.deb ...
Unpacking autopoweroff-gui (4.2.0) ...
dpkg: dependency problems prevent configuration of autopoweroff-gui:
 autopoweroff-gui depends on python-gi; however:
  Package python-gi is not installed.

dpkg: error processing package autopoweroff-gui (--install):
 dependency problems - leaving unconfigured
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu3) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu3) ...
Errors were encountered while processing:
 autopoweroff-gui
```
There is no `python-gi` package. I installed `python-gi-dev`, but installer still complains.

> If you use apt instead of dpkg, the dependencies will be automatically loaded. Always use apt, never dpkg.

This does not resolve the issue.

```
$ sudo apt install ./autopoweroff-daemon_4.2.0_all-ubuntu-22.04.deb ./autopoweroff-gui_4.2.0_all-ubuntu-20.04.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'autopoweroff-daemon' instead of './autopoweroff-daemon_4.2.0_all-ubuntu-22.04.deb'
Note, selecting 'autopoweroff-gui' instead of './autopoweroff-gui_4.2.0_all-ubuntu-20.04.deb'
autopoweroff-daemon is already the newest version (4.2.0).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 autopoweroff-gui : Depends: python-gi but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by deragon** [comment]
Sorry for the late response.  My life was busy.

You are installing 20.04 deb file on 22.04.  This is why you get the errors.  Please download the files meant for 22.04 at https://github.com/deragon/autopoweroff/releases.
